import assert from "node:assert/strict";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  generateMakersPromptData,
  loadPromptSpec,
  validatePromptSpec,
} from "../scripts/prompt-data-lib.mjs";

test("canonical prompt has stable modules examples styles and limits", async () => {
  const spec = await loadPromptSpec("shared/combine-prompt.json");
  assert.equal(spec.schema_version, 1);
  assert.equal(spec.temperature, 0.85);
  assert.equal(spec.system_modules.filter((item) => item.enabled).length, 8);
  assert.equal(spec.examples.filter((item) => item.enabled).length, 15);
  assert.deepEqual(
    spec.styles.map(({ id, weight }) => [id, weight]),
    [
      ["invented-word", 0.30],
      ["concrete-scene", 0.25],
      ["cross-domain", 0.15],
      ["mixed-language", 0.10],
      ["action-description", 0.10],
      ["idiom", 0.05],
      ["past-present", 0.05],
    ],
  );
  assert.deepEqual(spec.limits, {
    avoid_words: 30,
    community_examples: 8,
    bounty_candidates: 12,
  });
});

test("prompt validation rejects duplicate ids and invalid weights", () => {
  assert.throws(
    () => validatePromptSpec({
      schema_version: 1,
      temperature: 0.85,
      system_modules: [
        { id: "same", enabled: true, order: 1, content: "甲" },
        { id: "same", enabled: true, order: 2, content: "乙" },
      ],
      examples: [],
      styles: [
        { id: "only", enabled: true, label: "唯一", guidance: "唯一", weight: 0.5 },
      ],
      limits: { avoid_words: 30, community_examples: 8, bounty_candidates: 12 },
    }),
    /duplicate system_modules id|style weights must sum to 1/,
  );
});

test("generator writes a V8-safe JavaScript data module", async () => {
  const root = await mkdtemp(join(tmpdir(), "prompt-data-"));
  const outputPath = join(root, "prompt-data.js");
  await generateMakersPromptData({ root: ".", outputPath });
  const generated = await readFile(outputPath, "utf8");
  assert.match(generated, /^\/\/ Generated by scripts\/generate-makers-prompt-data\.mjs/m);
  assert.match(generated, /export const PROMPT_SPEC = /);
  assert.doesNotMatch(generated, /node:fs|process\.env|require\(/);
});

test("committed generated prompt data is current", async () => {
  const root = await mkdtemp(join(tmpdir(), "prompt-current-"));
  const outputPath = join(root, "prompt-data.js");
  await generateMakersPromptData({ root: ".", outputPath });
  assert.equal(
    await readFile(outputPath, "utf8"),
    await readFile("edge-functions/_generated/prompt-data.js", "utf8"),
  );
});
