import assert from "node:assert/strict";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  generateMakersPromptData,
  loadPromptSpec,
  validatePromptSpec,
} from "../scripts/prompt-data-lib.mjs";

test("canonical prompt has stable modules examples styles and limits", async () => {
  const spec = await loadPromptSpec("shared/combine-prompt.json");
  assert.equal(spec.schema_version, 1);
  assert.equal(spec.temperature, 0.85);
  assert.equal(spec.system_modules.filter((item) => item.enabled).length, 8);
  assert.equal(spec.examples.filter((item) => item.enabled).length, 15);
  assert.deepEqual(
    spec.styles.map(({ id, weight }) => [id, weight]),
    [
      ["invented-word", 0.30],
      ["concrete-scene", 0.25],
      ["cross-domain", 0.15],
      ["mixed-language", 0.10],
      ["action-description", 0.10],
      ["idiom", 0.05],
      ["past-present", 0.05],
    ],
  );
  assert.deepEqual(spec.limits, {
    avoid_words: 30,
    community_examples: 8,
    bounty_candidates: 12,
  });
});

test("prompt validation rejects duplicate ids", async () => {
  const spec = await loadPromptSpec("shared/combine-prompt.json");
  spec.system_modules[1].id = spec.system_modules[0].id;
  assert.throws(
    () => validatePromptSpec(spec),
    /duplicate system_modules id/,
  );
});

test("prompt validation rejects string style weights", async () => {
  const spec = await loadPromptSpec("shared/combine-prompt.json");
  spec.styles[0].weight = "0.3";
  assert.throws(
    () => validatePromptSpec(spec),
    /styles weight must be a finite number/,
  );
});

test("prompt validation rejects malformed module records", async () => {
  const paddedId = await loadPromptSpec("shared/combine-prompt.json");
  paddedId.system_modules[0].id = " identity ";
  assert.throws(
    () => validatePromptSpec(paddedId),
    /system_modules id must not have surrounding whitespace/,
  );

  const missingOrder = await loadPromptSpec("shared/combine-prompt.json");
  delete missingOrder.system_modules[0].order;
  assert.throws(
    () => validatePromptSpec(missingOrder),
    /system_modules order must be an integer/,
  );

  const missingContent = await loadPromptSpec("shared/combine-prompt.json");
  delete missingContent.system_modules[0].content;
  assert.throws(
    () => validatePromptSpec(missingContent),
    /system_modules content must be a non-empty string/,
  );
});

test("prompt validation rejects malformed example and style records", async () => {
  const numericExampleId = await loadPromptSpec("shared/combine-prompt.json");
  numericExampleId.examples[0].id = 123;
  assert.throws(
    () => validatePromptSpec(numericExampleId),
    /examples id must be a string/,
  );

  const missingInput = await loadPromptSpec("shared/combine-prompt.json");
  delete missingInput.examples[0].input.a;
  assert.throws(
    () => validatePromptSpec(missingInput),
    /examples input\.a must be a non-empty string/,
  );

  const nonBooleanEnabled = await loadPromptSpec("shared/combine-prompt.json");
  nonBooleanEnabled.styles[0].enabled = "true";
  assert.throws(
    () => validatePromptSpec(nonBooleanEnabled),
    /styles enabled must be a boolean/,
  );
});

test("generator writes a V8-safe JavaScript data module", async () => {
  const root = await mkdtemp(join(tmpdir(), "prompt-data-"));
  const outputPath = join(root, "prompt-data.js");
  await generateMakersPromptData({ root: ".", outputPath });
  const generated = await readFile(outputPath, "utf8");
  assert.match(generated, /^\/\/ Generated by scripts\/generate-makers-prompt-data\.mjs/m);
  assert.match(generated, /export const PROMPT_SPEC = /);
  assert.doesNotMatch(generated, /node:fs|process\.env|require\(/);
});

test("committed generated prompt data is current", async () => {
  const root = await mkdtemp(join(tmpdir(), "prompt-current-"));
  const outputPath = join(root, "prompt-data.js");
  await generateMakersPromptData({ root: ".", outputPath });
  assert.equal(
    await readFile(outputPath, "utf8"),
    await readFile("edge-functions/_generated/prompt-data.js", "utf8"),
  );
});
